### PR TITLE
Django 2.2

### PR DESCRIPTION
**Pull request by aletson**
ref: #136

### CODE REVIEW

**Comment by aletson** [comment]
When running `manage.py runserver` it mentions 20 outstanding migrations. The app still works so I don't know if I care but I do get an error running `manage.py migrate` on a local test so maybe we should eventually I don't know.

**Comment by rjmagley** [comment]
is it mentioning migrations on your local test environment, or on the beta server's log messages?

**Comment by aletson** [comment]
@rjmagley ok so don't be mad but it's been saying that on test, beta, and live since i moved from 1.4 to 1.5 way back when

**Comment by aletson** [comment]
i think it's like, the actual django core migrations

which i've been ignoring

**Comment by rjmagley** [comment]
with the votefinder source code we strive for hilarity

**Pull request merged**
